version: '3.8'

services:
  api:
    build: 
      context: ./Microservice_Flask   
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"   
    environment:
      - FLASK_ENV=development  
    volumes:
      - ./Microservice_Flask:/api   
    networks:
      - ImageDatabase   
 
  mongo:
    image: mongo   
    networks:
      - ImageDatabase  
    ports:
      - "27017:27017"   
    restart: always   

  api-node:
    build:
      context: ./Microservice_Nest
      dockerfile: Dockerfile   
    ports:
      - "3333:3333"   
    networks:
      - ImageDatabase  
 
networks:
  ImageDatabase:  # Define a rede
